### PR TITLE
add search functionality (issue #11)

### LINKED ISSUE #11: Add search functionality

### PR DESCRIPTION
**Pull request by ananafrida**

### CODE REVIEW

**Review by n-aggarwal — CHANGES_REQUESTED** [review]
The search function is very basic. It only looks if an artist's name starts with the exact same letters. Instead use fuzzy search and match it against either the artist or the song. 

An example of what was weird is that I have an "artist d" but when I search "d" it doesn't show up.

**Comment by ananafrida** [comment]
Good debugging skills. Fixed!

**Comment by n-aggarwal** [comment]
Could you please resolve the conflicts. I will merge it then.

**Comment by ananafrida** [comment]
Merge conflict resolved.

**Review by n-aggarwal — APPROVED** [review]
I am trusting you with this, since I am in bed, and can't review it.

**Pull request merged**
